@startuml

skinparam packageStyle folder

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList

package se.hig.oodp.lab.model {
    class Vertex2D {
        -x: double
        -y: double
        +Vertex2D(x:double, y:double)
        +getX(): double
        +getY(): double
        +moveBy(dx:double, dy:double): Vertex2D
        +rotate(ref:Vertex2D, angle:double): Vertex2D
        +scale(ref:Vertex2D, x_factor:double, y_factor:double): Vertex2D
    }
}

package se.hig.oodp.lab.model.figure {
    class Point {
        -center: Vertex2D
        +Point(center:Vertex2D)
        +moveBy(dx:double, dy:double): Vertex2D
        +getCenter(): Vertex2D
    }

    class Line {
        -center: Vertex2D
        -v0: Vertex2D
        -v1: Vertex2D
        +Line(v0:Vertex2D,v1:Vertex2D)
        +moveBy(dx:double, dy:double): Vertex2D
        +rotate(ref:Vertex2D, angle:double): Vertex2D
        +scale(ref:Vertex2D, x_factor:double, y_factor:double): Vertex2D
        +getCenter(): Vertex2D
    }
}

se.hig.oodp.lab.model +-- se.hig.oodp.lab.model.figure





@enduml
